[package]
name = "bark-build"
version = "0.1.0"
edition = "2024"

[dependencies]
bark = { path = "../bark" }
image = "0.25"
intel_tex_2 = "0.5"
obj-rs = "0.7"
rayon = "1.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
twox-hash = "2.1.2"
wesl = { version = "0.4", features = ["naga-ext"] }
